services:
  database:
    image: postgres:13

    environment:
      POSTGRES_USER: trelloAdmin
      POSTGRES_PASSWORD: trello2024
      POSTGRES_DB: trelloDatabase

    ports:
      - "8080:5432"

    volumes:
      - db:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
volumes:
  db:
